### ISSUE TITLE
Issue with clicking "Publish" when the publish_from is filled

### ISSUE THREAD

**Issue by somatonic** [formmailer/SchedulePages#10]
The latest pull request with the beforeSave hook to clear publish_from clearing when unpublishing is buggy. If I fill in the date and hit "Publish" it also clears the publish from field and shows 2 error message which makes no sense.

A quick debug shows that the beforeSave hook from Michael is getting called 2 times, cause you already have a afterSave hook that changes the page to unpublished and saves the page, thus the beforeSave hook gets called again, which results in the wrong behaviour.

When I add a flag to skip any further saves from the beforeSave hook it works again as it should and the published_from field doesn't get cleared.

My change:

```
public function beforeSave($event) {
		$page = $event->arguments[0];

		// Clear the publish_from field automatically when the page is manually
		// unpublished. This prevents the page from being unintentionally
		// re-published on the next cron run.
		
		// prevent this hook being run two times
		if($page->schedulerSkip) return;
		
		// wire("log")->save("scheduler-debug", "status: $page->status"); // debug to see

		if ($page->isChanged('status') && $page->is(Page::statusUnpublished) && $page->publish_from) {
			$this->session->error($this->_("“Publish From Date” field was cleared to prevent the page from being unintentionally re-published on the next Lazy Cron run."));
			$page->publish_from = null;
			$page->save('publish_from');
		}
		
		// set flag to prevent multiple runs
		$page->schedulerSkip = true;
	}
````

**Comment by MichaelvanLaar** [comment]
Thank you very much for bugfixing this. As I always like to stress, I’m not a programmer, especially not a backend programmer. ;-)

**Comment by somatonic** [comment]
No problem Michael. This is a tricky one.  I suggest to always test a little more than what's being implemented. ;) most often a fix introduces a new bug.

**Comment by formmailer** [comment]
Thank you for the update Soma!
Commited the changes.
